### ISSUE TITLE
Проглотил ошибку

### ISSUE THREAD

**Issue by vladimirkoba** [Arkanium77/ArkOfTests#10]
https://github.com/Arkanium77/ArkOfTests/blob/1fec8da9ccb1aef113a2a77c76ddaa72d936faad/src/main/java/team/isaz/framework/ArkOfTests.java#L143

То есть если метод исполнялся, и с чем-то вылетел, ты напишешь чуваку - FALSE)

**Comment by Arkanium77** [comment]
Was fixed in the InformativeAsserts branch and added to the wizard with commit #7ccd0b3.
