### ISSUE TITLE
Недружелюбные ассерты

### ISSUE THREAD

**Issue by vladimirkoba** [Arkanium77/ArkOfTests#11]
https://github.com/Arkanium77/ArkOfTests/blob/1fec8da9ccb1aef113a2a77c76ddaa72d936faad/src/main/java/team/isaz/framework/ArkOfAsserts.java#L9

В ассертах все же приняты говорить, как минимум, что ожидалось и что пришло, иначе по ним будет очень грустно отлаживаться)

**Comment by Arkanium77** [comment]
Was fixed in the InformativeAsserts branch and added to the wizard with commit #7ccd0b3.
