### ISSUE TITLE
Неуместный CheckedException

### ISSUE THREAD

**Issue by vladimirkoba** [Arkanium77/ArkOfTests#2]
https://github.com/Arkanium77/ArkOfTests/blob/1fec8da9ccb1aef113a2a77c76ddaa72d936faad/src/main/java/team/isaz/framework/ArkOfTests.java#L40

Смотри, это же класс для запуска тестов, который запускается один раз в тестовом коде. Какой обработки ошибки ты хочешь от пользователя?) 

Теперь ему нужно все либо в try-catch заворачивать, либо дальше прокидывать. Некомильфо)

**Comment by Arkanium77** [comment]
Accepted in commit #8309bdc
