### ISSUE TITLE
Поднять в отдельный класс

### ISSUE THREAD

**Issue by vladimirkoba** [Arkanium77/ArkOfTests#3]
https://github.com/Arkanium77/ArkOfTests/blob/1fec8da9ccb1aef113a2a77c76ddaa72d936faad/src/main/java/team/isaz/framework/ArkOfTests.java#L60

Кажется хорошим кандидатом на выделение в отдельный класс. Логика не зависит ни от чего и может в будущем меняться

**Comment by Arkanium77** [comment]
Was fixed in the InformativeAsserts branch and added to the wizard with commit #7ccd0b3.
