### ISSUE TITLE
Не самое удачное наименование

### ISSUE THREAD

**Issue by vladimirkoba** [Arkanium77/ArkOfTests#4]
https://github.com/Arkanium77/ArkOfTests/blob/1fec8da9ccb1aef113a2a77c76ddaa72d936faad/src/main/java/team/isaz/framework/ArkOfTests.java#L79

testClasses - возникает ощущение, что это непонятный тестовый класс. Понятно, что оно из-за особенностей глагола to test возникает, но лучше заменить на что-то в духе runTest :)

**Comment by Arkanium77** [comment]
Accepted in commit #8309bdc
