### ISSUE TITLE
Неправильное логгирование

### ISSUE THREAD

**Issue by vladimirkoba** [Arkanium77/ArkOfTests#5]
https://github.com/Arkanium77/ArkOfTests/blob/1fec8da9ccb1aef113a2a77c76ddaa72d936faad/src/main/java/team/isaz/framework/ArkOfTests.java#L84

На таком логгирование ты съедаешь весь стектрейс, что бывает критично. Вместо этого используй конструкцию logger.error("Some error", e);

**Comment by Arkanium77** [comment]
Accepted in commit #8309bdc
