### ISSUE TITLE
Всё статичное

### ISSUE THREAD

**Issue by vladimirkoba** [Arkanium77/ArkOfTests#6]
Ты написал в комментариях, почему так сделал, и это хорошо. Но есть вариант проще. Если хотелось поддержать интерфейс, как на слайде, то просто создай класс ArcTestFramework с одним статичным методом, в котором уже вызови обычный объект new ArcTestF блаблабла

**Comment by Arkanium77** [comment]
Was fixed in the InformativeAsserts branch and added to the wizard with commit #7ccd0b3.
