### ISSUE TITLE
Выделить в отдельный класс

### ISSUE THREAD

**Issue by vladimirkoba** [Arkanium77/ArkOfTests#8]
https://github.com/Arkanium77/ArkOfTests/blob/1fec8da9ccb1aef113a2a77c76ddaa72d936faad/src/main/java/team/isaz/framework/ArkOfTests.java#L174

Получение классов из пакетов - еще один хороший кандидат на вынесение в отдельный класс

**Comment by Arkanium77** [comment]
Was fixed in the InformativeAsserts branch and added to the wizard with commit #7ccd0b3.
