### ISSUE TITLE
Выделить в метод

### ISSUE THREAD

**Issue by vladimirkoba** [Arkanium77/ArkOfTests#9]
https://github.com/Arkanium77/ArkOfTests/blob/1fec8da9ccb1aef113a2a77c76ddaa72d936faad/src/main/java/team/isaz/framework/ArkOfTests.java#L181

Смесь декларативного и императивного стиля - это прям не очень. Подними то, что происходит в map в отдельный метод

**Comment by Arkanium77** [comment]
Accepted in commit #8309bdc
